accounts/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('me/', views.index, name='my_account'),
    path('<str:username>/', views.AccountView.as_view(), name='account'),
]

apps/urls.py
from django.urls import path

from .views import AppsView, app_view, post_comment

app_name = 'apps'
urlpatterns = [
    path('', AppsView.as_view(), name='apps'),
    path('<int:pk>/', app_view, name='app'),
    path('post_comment/', post_comment, name='post_comment'),
]

ba6tati/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('auth/', include('user_auth.urls', namespace='auth')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('apps/', include('apps.urls', namespace='apps')),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
]

user_auth/urls.py
from django.urls import path

from . import views

app_name = 'user_auth'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

accounts/models.py
from django.db import models

# Create your models here.

apps/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone

from user_auth.models import User

class App(models.Model):
    PLATFORMS = [
        ('win', 'Windows'),
        ('mac', 'MacOS'),
        ('ios', 'iOS'),
        ('android', 'Android'),
        ('linux', 'Linux'),
    ]
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=200)
    version = models.CharField(max_length=200) # TODO: change to version
    platforms = ArrayField(models.CharField(max_length=100), blank=True, default=list)
    release_date = models.DateField()
    tags = ArrayField(models.CharField(max_length=200))
    price = models.FloatField(default=0)
    downloads = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    publish_datetime = models.DateTimeField(default=timezone.now)
    likes = ArrayField(models.CharField(max_length=200), default=list)
    
    def __str__(self):
        return f'{self.app.name} | {self.user.username} | {self.text}'

core/models.py
from django.db import models

# Create your models here.

user_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    first_name = None
    last_name = None
    
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',  # Add this line
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='groups',
    )
    
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',  # Add this line
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

apps/forms.py
from django import forms

class PostCommentForm(forms.Form):
    text = forms.CharField(max_length=200, required=True)

user_auth/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import EmailField

from .models import User

class LoginForm(AuthenticationForm):
    pass

class RegisterForm(UserCreationForm):
    email = EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required

from user_auth.models import User

@login_required
def index(request):
    user = request.user
    return render(request, 'account/index.html', {'user': user})

class AccountView(DetailView):
    model = User
    template_name = "account/account.html"
    
    def get_object(self, queryset=None):
        # Get the username from the URL
        username = self.kwargs.get('username')
        # Retrieve the user object based on the username
        return get_object_or_404(User, username=username)

apps/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.http import Http404

from .models import App, Comment
from .forms import PostCommentForm

class AppsView(ListView):
    template_name = "apps/index.html"
    context_object_name = "latest_apps"

    def get_queryset(self):
        return App.objects.order_by('release_date')[:20]
    
def app_view(request, pk):
    comment_form = PostCommentForm()
    app = get_object_or_404(App, pk=pk, active=True)
    is_authenticated = request.user.is_authenticated
    comments = Comment.objects.filter(app=app)

    return render(request, 'apps/app.html', {'app': app, 'comments': comments, 'is_authenticated': is_authenticated, 'comment_form': comment_form})

def post_comment(request):
    if request.method == 'POST':
        app = get_object_or_404(App, pk=int(request.POST.get('app_pk')))
        form = PostCommentForm(request.POST)
        
        if form.is_valid():
            print('Form is valid!')
            comment = Comment.objects.create(user=request.user, app=app, text=form.cleaned_data['text'])
            comment.save()
        else:
            print(form.errors)
        return redirect('apps:app', pk=app.pk)
    
    return Http404

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

def index(request):
    return render(request, 'core/index.html', {'request': request})

def contact(request):
    
    return render(request, 'core/contact.html')

user_auth/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login, logout
from django.views.generic import TemplateView, DetailView

from .forms import RegisterForm
from .models import User

class UserLoginView(LoginView):
    template_name = 'user_auth/login.html'

def logout_view(request):
    logout(request)
    return redirect('auth:login')

"""


class UserProfileView(DetailView):
    model = models.User
    template_name = 'user_auth/profile.html'
"""

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            
            if user:
                login(request, user)
                return redirect('home')  # Redirect to a success page or home
            else:
                # Handle case where user is not returned
                print("User object is None")
                
            return redirect('home')
    else:
        form = RegisterForm()
            
    return render(request, 'user_auth/register.html', {'form': form})

apps/templates/apps/app.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ app.name }}</h1>
    <h3>{{ app.version }}</h3>
    {% if app.tags %}
        <h5>{{ app.tags }}</h5>
    {% endif %}
    <hr>
    <p>{{ app.description }}</p>
    <hr>
    {% if is_authenticated %}
    <form method="post" action="{% url 'apps:post_comment' %}">
        {% csrf_token %}
        <input type="hidden" name="app_pk" value="{{ app.pk }}">

        {{ comment_form.as_p }}

        {% if comment_form.errors %}
            <div class="errorlist">
                {% for field in comment_form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}

        <button type="submit">Post</button>
    </form>
    {% else %}
    <h4>Login to post comments</h4>
    {% endif %}

    {% for comment in comments %}
        <a href="{% url 'accounts:account' comment.user.username %}">{{ comment.user.username }}</a>
        <p>{{ comment.text }}</p>
        <h5>{% if comment.likes.all.count > 0 %}{{ comment.likes.all.count }}{% else %}0{% endif %} likes | {{ comment.publish_datetime }}</h5>
    {% endfor %}

{% endblock %}

apps/templates/apps/index.html
{% extends 'base.html' %}

{% block content %}
    <ul>
    {% for app in latest_apps %}
        <li><a href="{% url 'apps:app' app.pk %}">{{ app.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

core/templates/core/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>Contact</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home</h1>

    {% if request.user.is_authenticated %}
    <h3>Logged in</h3>
    {% endif %}
{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ba6taTi's Website</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'core:home' %}"> Home </a></li>
            <li><a href="{% url 'apps:apps' %}"> Apps </a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="{% url 'auth:login' %}">Login</a></li>
            <li><a href="{% url 'auth:logout' %}">Logout</a></li>
        </ul>
    </nav>
    {% block content %}
        
    {% endblock %}
</body>
</html>

user_auth/templates/user_auth/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>

    <form method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        {{ form.username }}

        {% if form.username.errors %}
            <div class="text-danger">
                {{ form.username.errors }}
            </div>
        {% endif %}

        {{ form.password }}

        {% if form.password.errors %}
            <div class="text-danger">
                {{ form.password.errors }}
            </div>
        {% endif %}

        <button type="submit">Login</button>
    </form>

{% endblock %}

user_auth/templates/user_auth/profile.html
{% extends 'base.html' %}

<h1>Profile</h1>

user_auth/templates/user_auth/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Sign Up</button>
    </form>
{% endblock %}